import {
  existsSync,
  readdirSync,
  readFileSync,
  readSync,
  writeFileSync,
  writeSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import type { CliPrinter } from '../cli-output.printer.js';

export interface BundleArchiveRegistrationOptions {
  readonly patchImportByDefault?: boolean;
}

export function writeBundleArchiveAssetRegistry(hostRoot: string): void {
  const bundleDir = join(hostRoot, '.bundle', 'rnm');
  const hasBlobUtilAssetFileSystem = packageJsonHasDependency(
    hostRoot,
    'react-native-blob-util',
  );
  const archiveFiles = existsSync(bundleDir)
    ? readdirSync(bundleDir)
        .filter((file) => /\.tar\.gz$/u.test(file))
        .sort((a, b) => a.localeCompare(b))
    : [];
  const entries = archiveFiles.map((file) => {
    const archiveUrl = `.bundle/rnm/${file}`;
    return `  ${JSON.stringify(archiveUrl)}: Image.resolveAssetSource(require(${JSON.stringify(`./${archiveUrl}`)}))?.uri,`;
  });
  const contents = [
    '/* Auto-generated by @bunin/react-native-micro-frontend. */',
    "import * as React from 'react';",
    "import * as ReactJsxRuntime from 'react/jsx-runtime';",
    "import * as ReactNative from 'react-native';",
    '// @ts-ignore React Native exposes this Metro asset registry subpath at runtime.',
    "import * as ReactNativeAssetRegistry from 'react-native/Libraries/Image/AssetRegistry';",
    ...(hasBlobUtilAssetFileSystem
      ? ["import ReactNativeBlobUtil from 'react-native-blob-util';"]
      : []),
    "import * as ReactNativeMicroFrontend from '@bunin/react-native-micro-frontend';",
    "import * as ReactNativeMicroFrontendRuntime from '@bunin/react-native-micro-frontend/runtime';",
    ...(entries.length > 0 ? ["import { Image } from 'react-native';"] : []),
    hasBlobUtilAssetFileSystem
      ? "import { createReactNativeBlobUtilAssetFileSystem, registerBundleArchiveAssetFileSystem, registerBundleArchiveAssets, registerBundleArchiveExternalModules } from '@bunin/react-native-micro-frontend/bundle-archive';"
      : "import { registerBundleArchiveAssets, registerBundleArchiveExternalModules } from '@bunin/react-native-micro-frontend/bundle-archive';",
    '',
    'export const bundleArchiveAssets = {',
    ...entries,
    '} as const;',
    '',
    'export const bundleArchiveExternalModules = {',
    "  'react': React,",
    "  'react/jsx-runtime': ReactJsxRuntime,",
    "  'react-native': ReactNative,",
    "  'react-native/Libraries/Image/AssetRegistry': ReactNativeAssetRegistry,",
    "  '@bunin/react-native-micro-frontend': ReactNativeMicroFrontend,",
    "  '@bunin/react-native-micro-frontend/runtime': ReactNativeMicroFrontendRuntime,",
    '} as const;',
    '',
    'registerBundleArchiveAssets(bundleArchiveAssets);',
    'registerBundleArchiveExternalModules(bundleArchiveExternalModules);',
    ...(hasBlobUtilAssetFileSystem
      ? [
          'registerBundleArchiveAssetFileSystem(createReactNativeBlobUtilAssetFileSystem(ReactNativeBlobUtil));',
        ]
      : []),
    '',
  ].join('\n');

  writeFileSync(join(hostRoot, 'rnm.bundle-archives.ts'), contents);
}

export function ensureBundleArchiveRegistration(
  hostRoot: string,
  flags: Readonly<Record<string, string | boolean>>,
  printer: CliPrinter,
  options: BundleArchiveRegistrationOptions = {},
): void {
  writeBundleArchiveAssetRegistry(hostRoot);
  registerBundleArchiveImport(hostRoot, flags, printer, options);
}

export function registerBundleArchiveImport(
  hostRoot: string,
  flags: Readonly<Record<string, string | boolean>>,
  printer: CliPrinter,
  options: BundleArchiveRegistrationOptions = {},
): void {
  const entryPath =
    stringFlag(flags['host-entry']) ?? detectHostEntry(hostRoot);

  if (!entryPath) {
    printer.log(
      '[INFO] rnm.bundle-archives.ts generated. Import it from your Host entry file, or pass --host-entry <file> with --yes to patch automatically.',
    );
    return;
  }

  if (!shouldPatchBundleArchiveImport(flags, printer, entryPath, options)) {
    return;
  }

  const absoluteEntryPath = resolve(hostRoot, entryPath);

  if (!existsSync(absoluteEntryPath)) {
    printer.log(
      `[INFO] rnm.bundle-archives.ts generated, but Host entry was not found: ${entryPath}`,
    );
    return;
  }
  const current = readFileSync(absoluteEntryPath, 'utf8');

  if (current.includes('rnm.bundle-archives')) {
    printer.log(
      `[OK] Host archive asset registration already imported: ${entryPath}`,
    );
    return;
  }

  const importPath = toImportSpecifier(
    relative(dirname(absoluteEntryPath), join(hostRoot, 'rnm.bundle-archives')),
  );
  writeFileSync(absoluteEntryPath, `import '${importPath}';\n${current}`);
  printer.log(`[OK] Imported rnm.bundle-archives from ${entryPath}`);
}

function shouldPatchBundleArchiveImport(
  flags: Readonly<Record<string, string | boolean>>,
  printer: CliPrinter,
  entryPath: string,
  options: BundleArchiveRegistrationOptions,
): boolean {
  if (flags['no-register-archives'] === true) {
    printer.log('[SKIP] Host archive asset registration import was disabled.');
    return false;
  }

  if (
    flags['register-archives'] === true ||
    flags.yes === true ||
    options.patchImportByDefault === true
  ) {
    return true;
  }

  if (process.stdin.isTTY && process.stdout.isTTY) {
    return askYesNo(
      `Import rnm.bundle-archives from ${entryPath} so React Native can load copied archives? [y/N] `,
    );
  }

  printer.log(
    `[INFO] rnm.bundle-archives.ts generated. Re-run with --yes or --register-archives to import it from ${entryPath} automatically.`,
  );
  return false;
}

function askYesNo(question: string): boolean {
  writeSync(1, question);
  const buffer = Buffer.alloc(256);
  const bytesRead = readSync(0, buffer, 0, buffer.length, null);
  const answer = buffer.toString('utf8', 0, bytesRead).trim().toLowerCase();

  return answer === 'y' || answer === 'yes';
}

function detectHostEntry(hostRoot: string): string | undefined {
  for (const candidate of [
    'index.ts',
    'index.tsx',
    'index.js',
    'index.jsx',
    'src/index.ts',
    'src/index.tsx',
    'src/index.js',
    'src/index.jsx',
    'src/App.tsx',
    'src/App.ts',
    'src/App.jsx',
    'src/App.js',
  ]) {
    if (existsSync(join(hostRoot, candidate))) return candidate;
  }

  return undefined;
}

function toImportSpecifier(path: string): string {
  const withoutExtension = path.replace(/\.[cm]?[jt]sx?$/u, '');
  const posixPath = toPosixPath(withoutExtension);

  return posixPath.startsWith('.') ? posixPath : `./${posixPath}`;
}

function toPosixPath(path: string): string {
  return path.replaceAll('\\', '/');
}

function packageJsonHasDependency(root: string, packageName: string): boolean {
  const packageJsonPath = join(root, 'package.json');
  if (!existsSync(packageJsonPath)) return false;

  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as {
    readonly dependencies?: Readonly<Record<string, unknown>>;
    readonly devDependencies?: Readonly<Record<string, unknown>>;
    readonly optionalDependencies?: Readonly<Record<string, unknown>>;
  };

  return [
    packageJson.dependencies,
    packageJson.devDependencies,
    packageJson.optionalDependencies,
  ].some((dependencies) => dependencies?.[packageName] !== undefined);
}

function stringFlag(value: string | boolean | undefined): string | undefined {
  return typeof value === 'string' ? value : undefined;
}
