import type { MfeRegistry } from "@bunin/react-native-micro-frontend";
import { createEmptyRegistry } from "@bunin/react-native-micro-frontend";

/** Generated file descriptor. */
export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

const HEADER = "// -----------------------------------------------------------------------------\n// <auto-generated by @bunin/react-native-micro-frontend>\n// Do not edit this file manually. Regenerate it with `rnm sync`.\n// -----------------------------------------------------------------------------\n";

/**
 * Creates generated native integration files without writing them.
 *
 * @param registry Optional initial registry.
 * @returns Generated file contents for host integration.
 */
export function createGeneratedIntegrationFiles(registry: MfeRegistry = createEmptyRegistry()): readonly GeneratedFile[] {
  return [
    { path: "rnm.registry.json", contents: `${JSON.stringify(registry, null, 2)}\n` },
    { path: "rnm.native-contract.json", contents: `${JSON.stringify({ schemaVersion: 1, nativeHash: registry.hostNativeHash ?? null }, null, 2)}\n` },
    { path: "ios/Podfile.rnm.generated.rb", contents: `${HEADER.replaceAll("//", "#")}\n# Add MFE pods here through generated sync output.\n` },
    { path: "android/rnm.settings.generated.gradle", contents: `${HEADER}// Add generated MFE Gradle project includes here.\n` },
    { path: "android/rnm.generated.gradle", contents: `${HEADER}// Add generated MFE Android dependencies here.\n` },
    { path: "android/AndroidManifest.rnm.generated.xml", contents: `<!--\n${HEADER.replaceAll("//", "").trim()}\n-->\n<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\" />\n` },
  ];
}

/**
 * Creates the default TypeScript host config template.
 *
 * @returns react-native-micro-frontend.config.ts contents.
 */
export function createDefaultHostConfigTemplate(): string {
  return `import { defineReactNativeMicroFrontendConfig } from "@bunin/react-native-micro-frontend";\n\nexport default defineReactNativeMicroFrontendConfig({\n  reactNative: { minVersion: "0.70.0", hermes: "optional", newArchitecture: "supported" },\n  ota: { enabled: true, provider: "hot-updater", mode: "manual" },\n  nativeChangePolicy: "ask",\n  packageManager: { supported: ["bun", "deno", "npm", "pnpm", "yarn"], strategy: "follow-host" },\n  package: { sync: "manual", sharedStrategy: "strict-singleton" },\n  ios: { pods: "manual" },\n  android: { integration: "manual" },\n  mfes: {},\n});\n`;
}
