import { defineReactNativeMicroFrontendConfig } from '@bunin/react-native-micro-frontend';

export default defineReactNativeMicroFrontendConfig({
  reactNative: {
    minVersion: '0.70.0',
    hermes: 'required',
    newArchitecture: 'supported',
  },
  ota: {
    enabled: true,
    provider: 'hot-updater',
    mode: 'manual',
    existingHotUpdater: {
      strategy: 'reuse',
      configPath: './hot-updater.config.ts',
    },
  },
  nativeChangePolicy: 'ask',

  packageManager: {
    supported: ['bun', 'deno', 'npm', 'pnpm', 'yarn'],
    strategy: 'follow-host',
  },

  package: {
    sync: 'manual',
    sharedStrategy: 'strict-singleton',
  },

  ios: {
    pods: 'manual',
  },

  android: {
    integration: 'manual',
  },

  // Host policy stays here.
  // Runtime module registration lives in rnm.registry.json,
  // normally generated by `rnm add <mfe-name>`.
  mfes: {},
});
